/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package jdbc.program;

import java.util.*;
import javax.swing.DefaultListModel;
import jdbc.model.Mahasiswa;
import jdbc.service.MysqlMahasiswaService;
/**
 *
 * @author chloud
 */
public class JFrameUtama extends javax.swing.JFrame {
    private MysqlMahasiswaService service = new MysqlMahasiswaService();
    
    // Model untuk masing-masing JList
    private DefaultListModel<String> dlmId = new DefaultListModel<>();
    private DefaultListModel<String> dlmNama = new DefaultListModel<>();
    /**
     * Creates new form JFrameUtama
     */
    public JFrameUtama() {
        initComponents();
        // Hubungkan model ke komponen JList yang ada di desain form
        jListId.setModel(dlmId);
        jListNama.setModel(dlmNama);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListId = new javax.swing.JList<>();
        jLabelId = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jListNama = new javax.swing.JList<>();
        jLabelNama = new javax.swing.JLabel();
        jLabelKelola = new javax.swing.JLabel();
        jButtonAmbilSemuaData = new javax.swing.JButton();
        jLabelNamatitikdua = new javax.swing.JLabel();
        jTextFieldNama = new javax.swing.JTextField();
        jButtonTambahkan = new javax.swing.JButton();
        jTextFieldIdEdit = new javax.swing.JTextField();
        jTextFieldNamaEdit = new javax.swing.JTextField();
        jButtonEdit = new javax.swing.JButton();
        jTextFieldIdHapus = new javax.swing.JTextField();
        jTextFieldNamaHapus = new javax.swing.JTextField();
        jButtonHapus = new javax.swing.JButton();
        jButtonResetIndeks = new javax.swing.JButton();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane3.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setViewportView(jListId);

        jLabelId.setText("ID");

        jScrollPane2.setViewportView(jListNama);

        jLabelNama.setText("Nama");

        jLabelKelola.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabelKelola.setText("Kelola Data Mahasiswa");

        jButtonAmbilSemuaData.setText("Ambil Semua Data");
        jButtonAmbilSemuaData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAmbilSemuaDataActionPerformed(evt);
            }
        });

        jLabelNamatitikdua.setText("nama:");

        jTextFieldNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNamaActionPerformed(evt);
            }
        });

        jButtonTambahkan.setText("tambahkan");
        jButtonTambahkan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTambahkanActionPerformed(evt);
            }
        });

        jTextFieldIdEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldIdEditActionPerformed(evt);
            }
        });

        jTextFieldNamaEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNamaEditActionPerformed(evt);
            }
        });

        jButtonEdit.setText("Edit");
        jButtonEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditActionPerformed(evt);
            }
        });

        jButtonHapus.setText("Hapus");
        jButtonHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHapusActionPerformed(evt);
            }
        });

        jButtonResetIndeks.setText("Reset Indeks");
        jButtonResetIndeks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonResetIndeksActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelId)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelNama))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextFieldIdHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldNamaHapus)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonHapus))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButtonAmbilSemuaData)
                                    .addComponent(jLabelNamatitikdua)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jTextFieldIdEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextFieldNamaEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jButtonTambahkan))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButtonEdit))
                            .addComponent(jButtonResetIndeks)
                            .addComponent(jLabelKelola, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldNama))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(461, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelNama, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelId)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabelKelola)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jButtonAmbilSemuaData)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelNamatitikdua)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonTambahkan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldIdEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldNamaEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonEdit))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldIdHapus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldNamaHapus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonHapus))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonResetIndeks))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap(54, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAmbilSemuaDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAmbilSemuaDataActionPerformed
        // Kosongkan list di layar terlebih dahulu
        dlmId.clear();
        dlmNama.clear();

        // Ambil data terbaru dari database
        List<Mahasiswa> listMhs = service.getAll();

        // Iterasi hasil untuk ditampilkan ke GUI
        for (Mahasiswa mhs : listMhs) {
            dlmId.addElement(String.valueOf(mhs.getId()));
            dlmNama.addElement(mhs.getNama());
        }
    }//GEN-LAST:event_jButtonAmbilSemuaDataActionPerformed

    private void jButtonTambahkanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTambahkanActionPerformed
    String namaInput = jTextFieldNama.getText().trim();

        if (!namaInput.isEmpty()) {
            // Membuat objek baru dan menambahkannya ke database
            Mahasiswa mhsBaru = new Mahasiswa();
            mhsBaru.setNama(namaInput);

            service.add(mhsBaru);

            // Reset text field setelah berhasil menambahkan
            jTextFieldNama.setText("");

            // Refresh tampilan layar agar data baru langsung muncul
            jButtonAmbilSemuaDataActionPerformed(evt);
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Nama tidak boleh kosong!");
        }
    }//GEN-LAST:event_jButtonTambahkanActionPerformed

    private void jButtonEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditActionPerformed
    String idText = jTextFieldIdEdit.getText().trim();
        String namaBaru = jTextFieldNamaEdit.getText().trim();

        if (!idText.isEmpty() && !namaBaru.isEmpty()) {
            try {
                int id = Integer.parseInt(idText);

                // Bungkus ke dalam objek Mahasiswa
                Mahasiswa mhsUpdate = new Mahasiswa();
                mhsUpdate.setId(id);
                mhsUpdate.setNama(namaBaru);

                // Eksekusi update ke database
                service.update(mhsUpdate);

                // Bersihkan field edit setelah sukses
                jTextFieldIdEdit.setText("");
                jTextFieldNamaEdit.setText("");

                // Refresh JList di layar
                jButtonAmbilSemuaDataActionPerformed(evt);

                javax.swing.JOptionPane.showMessageDialog(this, "Data mahasiswa berhasil diperbarui!");
            } catch (NumberFormatException e) {
                javax.swing.JOptionPane.showMessageDialog(this, "ID harus berupa angka!");
            }
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "ID dan Nama Baru harus diisi untuk mengedit!");
        }
    }//GEN-LAST:event_jButtonEditActionPerformed

    private void jButtonHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHapusActionPerformed
    String idText = jTextFieldIdHapus.getText().trim();
    String namaHapus = jTextFieldNamaHapus.getText().trim();

        if (!idText.isEmpty() && !namaHapus.isEmpty()) {
            try {
                int id = Integer.parseInt(idText);

                // Ambil data mahasiswa dari database berdasarkan ID untuk validasi
                Mahasiswa mhsValidasi = service.getById(id); // Pastikan method getById(id) sudah ada di service

                if (mhsValidasi != null && mhsValidasi.getNama().equalsIgnoreCase(namaHapus)) {
                    // Jika ID dan Nama cocok, lakukan penghapusan
                    service.delete(id);

                    // Bersihkan field hapus
                    jTextFieldIdHapus.setText("");
                    jTextFieldNamaHapus.setText("");

                    // Refresh JList di layar
                    jButtonAmbilSemuaDataActionPerformed(evt);

                    javax.swing.JOptionPane.showMessageDialog(this, "Data mahasiswa berhasil dihapus!");
                } else {
                    javax.swing.JOptionPane.showMessageDialog(this, "Validasi gagal! ID dan Nama tidak cocok.");
                }
            } catch (NumberFormatException e) {
                javax.swing.JOptionPane.showMessageDialog(this, "ID harus berupa angka!");
            }
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "ID dan Nama harus diisi untuk menghapus!");
        }
    }//GEN-LAST:event_jButtonHapusActionPerformed

    private void jTextFieldNamaEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNamaEditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNamaEditActionPerformed

    private void jButtonResetIndeksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonResetIndeksActionPerformed
        // Mengosongkan tabel lewat service
        service.indexReset();

        // Langsung refresh layar agar JList menjadi kosong kembali
        jButtonAmbilSemuaDataActionPerformed(evt);

        javax.swing.JOptionPane.showMessageDialog(this, "Basis data berhasil dibersihkan!");
    }//GEN-LAST:event_jButtonResetIndeksActionPerformed

    private void jTextFieldNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNamaActionPerformed

    private void jTextFieldIdEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldIdEditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldIdEditActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameUtama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAmbilSemuaData;
    private javax.swing.JButton jButtonEdit;
    private javax.swing.JButton jButtonHapus;
    private javax.swing.JButton jButtonResetIndeks;
    private javax.swing.JButton jButtonTambahkan;
    private javax.swing.JLabel jLabelId;
    private javax.swing.JLabel jLabelKelola;
    private javax.swing.JLabel jLabelNama;
    private javax.swing.JLabel jLabelNamatitikdua;
    private javax.swing.JList<String> jListId;
    private javax.swing.JList<String> jListNama;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextFieldIdEdit;
    private javax.swing.JTextField jTextFieldIdHapus;
    private javax.swing.JTextField jTextFieldNama;
    private javax.swing.JTextField jTextFieldNamaEdit;
    private javax.swing.JTextField jTextFieldNamaHapus;
    // End of variables declaration//GEN-END:variables
}
